version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - bot_data:/app/data
    environment:
      - TZ=Europe/Moscow
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_USER_ID=${ADMIN_USER_ID}
    restart: always
    command: python app/main.py

volumes:
  bot_data: