version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - bot_data:/app/data
    environment:
      - TZ=Europe/Moscow
      - BOT_TOKEN=7207580139:AAGD32zSX_e6EWAI5kaFEoj0CMuywZ5nMBg
      - ADMIN_USER_ID=795051614
    restart: always
    command: python app/main.py

volumes:
  bot_data: